### ISSUE TITLE
Release 2.0.0 lacks `dist` folder

### ISSUE THREAD

**Issue by dominiks-cliqz** [simple-statistics/simple-statistics#150]
There is no `dist` folder here: https://github.com/simple-statistics/simple-statistics/tree/v2.0.0

(`dist` is still present in `v2.0.0-beta`.)

**Comment by tmcw** [comment]
Hi Dominik,

This is intentional: [dist is now gitignored](https://github.com/simple-statistics/simple-statistics/blob/master/.gitignore) but then [specifically included with package.json](https://github.com/simple-statistics/simple-statistics/blob/master/package.json#L12) so it is included in the npm package. This [follows the suggested workflow of npmcdn](https://npmcdn.com/#/), with the end result being:

* Since dist files are no longer in git, there are no gnarly git conflicts when multiple PRs rebuild dist
* Also less commit noise as people rebuild dist
* But the dist file is still available if you clone & build, or if you [use the npmcdn distribution](https://npmcdn.com/simple-statistics@2.0.0/dist/simple-statistics.min.js).

**Comment by dominiks-cliqz** [comment]
Hi Tom, thanks for explaining!

**Comment by court-jus** [comment]
So how should we do if we are using bower ?

**Comment by tmcw** [comment]
You can either

```
bower install https://github.com/simple-statistics/simple-statistics.git
```

Or use the CDN or something other than Bower. I'm sorry, but [bower is a drag on my time and the time of other open source project owners](https://github.com/mjackson/npm-http-server#bower-support), and it works against the flow of GitHub repos by requiring checked-in builds. Browserify, webpack, rollup, CDNs, JavaScript files - there are many other options, and I recommend any of them over Bower.

**Comment by tmcw** [comment]
There's also a bower.zip located at https://npmcdn.com/simple-statistics@2.0.1/bower.zip
