### ISSUE TITLE
Implement random sample with replacement

### ISSUE THREAD

**Issue by jdittrich** [simple-statistics/simple-statistics#173]
**Story:** As a user I would like to draw random samples with replacement to generate [bootstraps](https://en.wikipedia.org/wiki/Bootstrapping_(statistics)) (or, in general, generate a series of independent random values from an array).  

**Suggested implementation**: most natural would be adding an optional parameter to `shuffle` that allows to specify if the sample should be created with or without replacement.

**Comment by tmcw** [comment]
Good idea! Random sampling with replacement, as far as I can tell, can be implemented as something like

```
for sample count ->
  pick random integer from 0 to size of dataset
  add dataset[random integer] to sample
```

Which is faster than an equivalent shuffle, since shuffles that sample the entire dataset would need to be O(n) wrt the dataset, whereas this can be O(n) or whatever, for the size of the sample.
