### ISSUE TITLE
Linear time mode computation

### ISSUE THREAD

**Issue by Yomguithereal** [simple-statistics/simple-statistics#177]
Hello `simple-statistics`. Thanks for the awesome library.

I see that you chose to compute the mode by sorting the given array (which is cloned of course not to mutate the user's data) which runs in `O(n logn)` time.

Why not compute it in linear time by keeping track of the frequencies in linear time instead (it might be less fast because of JS engine optimizing `sort` to a certain extent but on large datasets, I doubt it).

**Comment by tmcw** [comment]
Sure! There's a slightly better answer to this one :)

This design decision was because of objects in JavaScript: they're kind of a disappointment. The nicely linear implementation of mode computation would look like:

```js
var things = [true, 'true', false, 'false', false];

var counts = things.reduce((memo, thing) => {
  if (typeof memo[thing] == 'number') {
    memo[thing]++;
  } else {
    memo[thing] = 1;
  }
  return memo;
}, Object.create(null));

var modeCount = 0;
var mode = undefined;

Object.keys(counts).forEach(key => {
  if (counts[key] > modeCount) {
    mode = key;
    modeCount = counts[key];
  }
});

mode;
modeCount;
```

Live example: http://mistakes.io/#0bee75cd0fce87af1d530772f0e63938

Since objects in JavaScript can only have string keys, 0 and '0' will be counted the same, and false, 'false'.

The [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) object solves that problem by having arbitrary typed keys, but using it would require upping simple-statistics's browser requirements quite a bit (right now they're ~ES3).

There might be a linear implementation that I'm missing that doesn't require ES6 and works with strict equality - I'd love to make this faster if we can.

**Comment by Yomguithereal** [comment]
Why not rely on some feature detection either when exporting the function or when applying it? Something like:

```js
typeof Map !== 'undefined';
```

Then we would have the best of both world, no? The `Map` object is quite optimized by recent browsers (even faster than plain objects in some use cases, notably this one).

But I agree this seems weird to expose different functions based on the engine's capabilities for  a library.

**Comment by tmcw** [comment]
How about a `modeFast` method, and expose both? That'd dodge concerns like testability (we'd have to fake out Map availability), debuggability (bug reports would be clear about which implementation was at fault), as well as make the performance characteristics clearly documentable.

**Comment by Yomguithereal** [comment]
I guess we'll need to do some kind of benchmark before taking a decision :). Because I boast it would be faster but this is mere conjecture :)

**Comment by Yomguithereal** [comment]
I guess that since it was implemented as `modeFast` I can close this issue :)
