### ISSUE TITLE
NaN versus throwing

### ISSUE THREAD

**Issue by Yomguithereal** [simple-statistics/simple-statistics#179]
Honest design question: why did you choose returning `NaN` in irrelevant cases, rather than throwing? I think most of languages would return a `NaN`-like value in this case but the fact is in languages like JavaScript or Java, `NaN` propagation is somewhat of a pain.

**Comment by tmcw** [comment]
Sure, so there were a few reasons for that decision:

* simple-statistics can be kind of performance-critical and I've encountered perf drawbacks with try/catch in the past. That said, JavaScript engines have gotten a lot better so this doesn't matter as much.
* In the functional style, I daydream about having [Maybe](http://package.elm-lang.org/packages/elm-lang/core/latest/Maybe) type objects instead of exception throwing.

That said, this might be something to change in a future version, since NaN-checking is indeed so rare in JavaScript-land. Anyone else want to chip in, for whether we should throw or return NaN?

**Comment by Yomguithereal** [comment]
> simple-statistics can be kind of performance-critical and I've encountered perf drawbacks with try/catch in the past. That said, JavaScript engines have gotten a lot better so this doesn't matter as much.

Sure, try-catch are to avoid for performance reasons. But I am not advocating to force the developer to rely on them but rather to view throwing errors as a mean to warn the developer that they are doing something probably inconsistent, meaning that they probably should check themselves whether their list is more than one items before computing this list's sample variance. Rather than having to check afterwards whether the returned value is a NaN (which is quite difficult to do in JavaScript because of the `isNaN` function ambiguity etc.).

> In the functional style, I daydream about having Maybe type objects instead of exception throwing.

Me too but I feel JavaScript is not there yet :)

**Comment by eikooc** [comment]
I am also in favor of throwing instead of returnung `NaN` for the same reasons that @Yomguithereal  are referencing

**Comment by tmcw** [comment]
Yep, I'm convinced: isNaN just isn't very convenient. I'm going to work on a new release today.
