### ISSUE TITLE
median algorithm complexity

### ISSUE THREAD

**Issue by Yomguithereal** [simple-statistics/simple-statistics#279]
I was just wondering what was the algorithm chosen for median/quantile computation. I think @mourner implemented it.

Is it `O(n log n)`? If so, should we try to implement the linear time median of medians algorithm?

https://en.wikipedia.org/wiki/Median_of_medians

**Comment by tmcw** [comment]
That's be a question for @mourner :)

**Comment by phoeagon** [comment]
The implementation is based on quickselect. https://en.wikipedia.org/wiki/Quickselect

Quickselect has an expectation of O(N). But since the implementation doesn't do randomized pivot selection (or maybe I missed it), you can carefully craft the input to make it O(N^2).

In practice, except for the case of crafted data, quick selection is almost always faster than deterministic median selection algorithm, due to a smaller constant omitted in the big O notation.

**Comment by mourner** [comment]
Thanks for the answer @phoeagon! Yes, I believe the current implementation is fast in practice and won't improve by switching to another median algorithm. However you can always prove me wrong with a PR.

**Comment by Yomguithereal** [comment]
@mourner Yup. I've checked a lot of benchmarks in lots of language recently concerning quickselect vs. median of medians and quickselect is in practice clearly on top. Thanks for the implementation :)
