### ISSUE TITLE
quantile() function produces unexpected results (undefined, nan)

### ISSUE THREAD

**Issue by jasonswearingen** [simple-statistics/simple-statistics#333]
using ```"simple-statistics": "^6.1.0"```

The following code produces a first quantile of ```NaN```, which seems an error:
```javascript
ss.quantile( [ 500, 468, 454, 469 ], [ 0.25, 0.5, 0.75 ])
```
> [ NaN, 461.5, 484.5 ]

The following code adds additional quantile, and in addition to producing unexpected ```undefined``` and ```NaN``` values, the 0.5 quantile is now missing (it was shown in the above test)
```javascript
ss.quantile( [ 500, 468, 454, 469 ],[ 0.05, 0.25, 0.5, 0.75, 0.95 ])
```
> [ undefined, NaN, NaN, 484.5, 500 ]

**Comment by tmcw** [comment]
Edited to remove editorializing. Thanks for the bug report, please vent elsewhere :), this is meant to be a productive space.

**Comment by gradynoonen** [comment]
It appears that this fix is not included in the current browser build. It looks like microbundle was introduced at the same time this was released, which seems relevant. I've verified that the fix is included in `dist/simple-statistics.js`, but not in `dist/simple-statistics.min.js` for v6.1.1. Also, `dist/simple-statistics.js` is now minified, which was not the case for v6.1.0. Hopefully this information is helpful. Please let me know if I can provide more information, or if there's anything I can do to help.
