### ISSUE TITLE
quest / feature request

### ISSUE THREAD

**Issue by npomfret** [simple-statistics/simple-statistics#367]
Is there a way to get multiple values from a single api call?  For example, I want to get the mean and standard deviation.  As far as I can see I need to make two API calls.  But to calc the latter the API needs to calc the former - an API call that returns not only the result but the intermediate results such as mean and variance would be great.

**Comment by tmcw** [comment]
That's a good question. I think the answer is a few things:

In the vast majority of cases, the duplicate computation will not be a bottleneck in your application. Mean, standard deviation, variance, min, max, etc - they're all O(n) operations, and written in such a way that they're [extremely fast](https://github.com/simple-statistics/simple-statistics/tree/master/benchmarks). I'd be surprised if they're ever a bottleneck in any application.

My gut is that returning multiple results, like an object of `{standardDeviation, mean, variance}` would make these algorithms less performant for small datasets, because it requires constructing an array or object or some other composite data type.

For the particular case, if you find that this a bottleneck, it's probably worthwhile to just vendor the code from simple-statistics into your project and do it inline, and keep the result from mean() around.

But, to reiterate - unless you've quantitatively identified this as a bottleneck, I wouldn't rush to optimize it. It's very, very unlikely that this is a bottleneck.

**Comment by npomfret** [comment]
@tmcw thanks for the reply.

I actually want the min, max, mean and standard deviation, and they could all be got with a single iteration of my dataset.  Now my dataset isn't massive, so currently it's not going to make any difference if I iterate over it 4 times, as you say.  But a new method call (`simpleStatistics(...)`?) that returns the lot would be nice - i'd certainly use it if it were there.

**Comment by Yomguithereal** [comment]
You can save one iteration currently by using the extent method. It’s not much but it’s still there :)
