### ISSUE TITLE
Deno fork

### ISSUE THREAD

**Issue by ergenekonyigit** [simple-statistics/simple-statistics#456]
Hi, I'm start building a simple-statistics package port for deno. This package will not only be a port. I will also be adding more functionalities it 🙂

https://deno.land/x/statistics
https://github.com/ergenekonyigit/statistics

**Comment by Yomguithereal** [comment]
I don't really get why you would do that @ergenekonyigit. The library already supports typescript and you can very well use it with deno likewise:

```js
import * as stats from 'https://cdn.pika.dev/simple-statistics@^7.0.8';
```

**Comment by ergenekonyigit** [comment]
As I said above, this package will not port at all, I was building a non-parametric statistics tests library a couple of years ago. https://github.com/ergenekonyigit/nemene I want to rebuild this library with deno and typescript, some utilities parts port from simple-statistics. Also, I referred simple-statistics in the README and telling you what I'm doing.

**Comment by mourner** [comment]
@ergenekonyigit so basically it's not a port, it's a fork. You might want to state so in the readme, in addition to specifying how exactly it differs from `simple-statistics` and fixing the license, so that it doesn't look like you just changed the name in the license copyright, merged JS and type files together, and pushed the code to `deno.land`.

**Comment by ergenekonyigit** [comment]
@mourner I've added information about the roadmap.

**Comment by tmcw** [comment]
🤷 Fine, have fun. You're welcome to contribute to this project, where I happily accept PRs, and  we already support Deno and TypeScript.

It's kind of rude to copy a project instead of forking or contributing, and to immediately change the copyright even though you weren't the one to spend years writing and maintaining the code, and to have a mysterious band of six onlookers who thumbs-down every comment from contributors here and thumbs-up your own, but who am I to judge.
