### ISSUE TITLE
Make testing utilities in test/approx.js available as part of the package

### ISSUE THREAD

**Issue by gvwilson** [simple-statistics/simple-statistics#486]
1.  People writing applications that use this library need to test their programs.
2.  The utility functions in `test/approx.js` are useful for doing this.
3.  Move them to `src/` and make them generally available.
4.  Provide a generalized comparator to implement "approximately deepEqual".

If this proposal is accepted, I volunteer to do the work.

**Comment by tmcw** [comment]
Fancier assertion libraries have `within` methods ([should](http://shouldjs.github.io/#assertion-within), [expect](https://github.com/Automattic/expect.js), [chai](https://www.chaijs.com/api/bdd/#method_within), [unexpected](https://unexpected.js.org/assertions/number/to-be-within/)), but these are indeed doing something different than what approx is doing (simple fuzzy range rather than relative standard error).

With that in mind, yep, seems like a good idea!

**Comment by gvwilson** [comment]
:+1:

**Comment by Yomguithereal** [comment]
@gvwilson I have assigned you

**Comment by tmcw** [comment]
Shipped in 7.3.0. Thanks @gvwilson! https://github.com/simple-statistics/simple-statistics/blob/master/CHANGELOG.md#730-2020-09-08
