### ISSUE TITLE
why is a math lib returning strings?

### ISSUE THREAD

**Issue by TheDirigible** [simple-statistics/simple-statistics#716]
cumulativeStdNormalProbability uses toFixed(), which returns a string.  This is not how you round.

**Comment by TheDirigible** [comment]
Ahh I see, the + returns it to a number.  That doesn't improve things
though, converting to string and back is a costly conversion.
Not sure why you don't just return the value?

**Comment by tmcw** [comment]
It's a normal distribution table, which has [either four or five digits of precision](https://www.investopedia.com/articles/active-trading/092914/normal-distribution-table-explained.asp), in this case, four.

Converting to a string and back is not a costly conversion, relative to virtually everything else. If that's actually a bottleneck in your application, that'd be surprising, but if it is based on a profile, and you have a faster technique, I'm more than happy to merge a pull request to limit significant digits in a faster way.

**Comment by TheDirigible** [comment]
Sure the value comes from a table with limited precision (I would argue too
limited - 6 digits is better for finance), but there's no reason for this
function to slow itself down in order to output the same.  The point of a
table lookup is to be fast.  The consumer is looking for a fast result, not
a value ready-made to be placed in a table.  Also a linear interpolation
between the 2 closest table entries would be more accurate.

toFixed() is 20x slower than alternatives
https://stackoverflow.com/questions/36529495/performance-tofixed-vs-math-floorx-10000

**Comment by mourner** [comment]
I agree that the original form of the issue report was not very productive, but the underlying criticism is sound — `toFixed` should be used only for formatting, not for numeric operations. In this case it's better not only as a potential micro-optimization, but also for consistency, since the table values are rounded numerically (with `Math.round(1e4 * value) / 1e4`):

https://github.com/simple-statistics/simple-statistics/blob/b4a9c787943534d46ce8405846858eb4866af47e/src/standard_normal_table.js#L12-L15

**Comment by TheDirigible** [comment]
I'm helping by pointing out the problem, sorry I don't have time to fix
it.  I don't even use this lib.
One of my app's biggest bottlenecks is millions of calls to cmlNormal, so
yeah little things can matter.
Sorry if I upset anyone!  I just found it kind of surprising in a math lib.
